/*
 * April 6th, 2020
 * Erika Graham
 * Program using String methods
 */

/**
 *
 * @author kikag
 */
public class FrmStringMethods extends javax.swing.JFrame {

    /**
     * Creates new form FrmStringMethods
     */
    public FrmStringMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        btnLength = new javax.swing.JButton();
        lblLengthAns = new javax.swing.JLabel();
        lblInstructions2 = new javax.swing.JLabel();
        txtCaps = new javax.swing.JTextField();
        btnCaps = new javax.swing.JButton();
        lblCapsAns = new javax.swing.JLabel();
        btnChar4 = new javax.swing.JButton();
        txtChar4 = new javax.swing.JTextField();
        lblInstructions3 = new javax.swing.JLabel();
        lblChar4Ans = new javax.swing.JLabel();
        btnIdentical = new javax.swing.JButton();
        txtIdent1 = new javax.swing.JTextField();
        lblInstructions4 = new javax.swing.JLabel();
        lblIdentical = new javax.swing.JLabel();
        btnFound = new javax.swing.JButton();
        txtIdent2 = new javax.swing.JTextField();
        lblInstructions5 = new javax.swing.JLabel();
        lblFoundAns = new javax.swing.JLabel();
        btnLong = new javax.swing.JButton();
        txtFound1 = new javax.swing.JTextField();
        lblInstructions6 = new javax.swing.JLabel();
        lblLongAns = new javax.swing.JLabel();
        btnReplace = new javax.swing.JButton();
        txtFound2 = new javax.swing.JTextField();
        lblInstructions7 = new javax.swing.JLabel();
        lblReplaceAns = new javax.swing.JLabel();
        txtLong = new javax.swing.JTextField();
        txtReplace = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 204));
        lblTitle.setText("SUPER STRING SOFTWARE");

        lblInstructions1.setText("Enter a String. The program will output the number of characters in the String.");

        btnLength.setText("Length");
        btnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLengthActionPerformed(evt);
            }
        });

        lblLengthAns.setText("...");

        lblInstructions2.setText("Enter a String using lowercase letters. The program will output the String in all capital letters.");

        btnCaps.setText("All Caps");
        btnCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapsActionPerformed(evt);
            }
        });

        lblCapsAns.setText("...");

        btnChar4.setText("4th Spot");
        btnChar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChar4ActionPerformed(evt);
            }
        });

        lblInstructions3.setText("Enter a String. The program will output the character at the fourth spot.");

        lblChar4Ans.setText("...");

        btnIdentical.setText("Identical?");
        btnIdentical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdenticalActionPerformed(evt);
            }
        });

        lblInstructions4.setText("Enter two Strings. The program will output whether or not they are identical.");

        lblIdentical.setText("...");

        btnFound.setText("Letter Found?");
        btnFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoundActionPerformed(evt);
            }
        });

        lblInstructions5.setText("Enter a String and a letter. The program will output whether or not the letter is found in the String.");

        lblFoundAns.setText("...");

        btnLong.setText("Characters 4 to 6");
        btnLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLongActionPerformed(evt);
            }
        });

        lblInstructions6.setText("Enter a String that is at least 8 characters long. The program will output characters 4 to 6.");

        lblLongAns.setText("...");

        btnReplace.setText("Replaces \"a\"");
        btnReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceActionPerformed(evt);
            }
        });

        lblInstructions7.setText("Enter a String that contains at least one \"a\". The program will then replace all occurences of the letter \"a\" with \"x\".");

        lblReplaceAns.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblInstructions4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtIdent1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(txtIdent2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnIdentical)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIdentical))
                                .addComponent(lblInstructions2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtChar4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(93, 93, 93)
                                                    .addComponent(btnChar4))
                                                .addComponent(lblInstructions3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChar4Ans))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(88, 88, 88)
                                            .addComponent(btnCaps)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCapsAns)))
                                    .addGap(11, 11, 11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)
                                        .addComponent(btnLength)
                                        .addGap(43, 43, 43)
                                        .addComponent(lblLengthAns))
                                    .addComponent(lblInstructions1)
                                    .addComponent(lblInstructions5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblInstructions7)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(117, 117, 117)
                                            .addComponent(btnReplace)
                                            .addGap(86, 86, 86)
                                            .addComponent(lblReplaceAns)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFound1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtFound2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(btnFound)
                                        .addGap(73, 73, 73)
                                        .addComponent(lblFoundAns))
                                    .addComponent(lblInstructions6)
                                    .addComponent(txtLong, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnLong)
                                        .addGap(81, 81, 81)
                                        .addComponent(lblLongAns)))
                                .addGap(16, 16, 16)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblInstructions1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLength)
                    .addComponent(lblLengthAns))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCaps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaps)
                    .addComponent(lblCapsAns))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChar4)
                    .addComponent(lblChar4Ans))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdentical)
                    .addComponent(lblIdentical)
                    .addComponent(txtIdent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFound)
                    .addComponent(lblFoundAns)
                    .addComponent(txtFound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblInstructions6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLong)
                    .addComponent(txtLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLongAns))
                .addGap(26, 26, 26)
                .addComponent(lblInstructions7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReplace)
                    .addComponent(lblReplaceAns)
                    .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLengthActionPerformed
        // declare variable to store the String and get the input
        String word = txtLength.getText();
        //output the number of characters of the string.
        lblLengthAns.setText(String.valueOf(word.length()));
    }//GEN-LAST:event_btnLengthActionPerformed

    private void btnCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapsActionPerformed
        // declare variable to store input
        String lowercase = txtCaps.getText();
        //outputs the String as uppercase
        lblCapsAns.setText(lowercase.toUpperCase());
    }//GEN-LAST:event_btnCapsActionPerformed

    private void btnChar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChar4ActionPerformed
        // declare variable to store input
        String fourth = txtChar4.getText();
        // outputs String's fourth character
        lblChar4Ans.setText(String.valueOf(fourth.charAt(3)));
    }//GEN-LAST:event_btnChar4ActionPerformed

    private void btnIdenticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdenticalActionPerformed
        // declare variables to store input
        String var1 = txtIdent1.getText();
        String var2 = txtIdent2.getText();
        // if statement that checks whether the two variables are the same or not
        if (var1.equals(var2))
        {
            lblIdentical.setText("They are identical");
        } else
        {
            lblIdentical.setText("They are not identical");
        }
    }//GEN-LAST:event_btnIdenticalActionPerformed

    private void btnFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoundActionPerformed
        // declare variables to store input
        String word = txtFound1.getText();
        String letter = txtFound2.getText();
        // check whether the letter is in the String or not and print the answer
        if ((word.indexOf(letter))>=0) //if the letter is in the string the letter
        {                              //will have a value of 0 or greater
            lblFoundAns.setText("The letter is in this String");
        } else if ((word.indexOf(letter))== -1) //if the letter is NOT in the string
        {                                   //the letter will have a value of less than 0 (-1)
            lblFoundAns.setText("The letter is not in this String");      
        }
    }//GEN-LAST:event_btnFoundActionPerformed

    private void btnLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLongActionPerformed
        // declare variable to store input
        String trimstring = txtLong.getText();
        //array to store the characters to be displayed later
        char stringindex []=new char [3];
        stringindex [0]=trimstring.charAt(3);
        stringindex [1]=trimstring.charAt(4);
        stringindex [2]=trimstring.charAt(5);
        //display the characters
        lblLongAns.setText(String.valueOf(stringindex [0])+ String.valueOf(stringindex [1])+ String.valueOf(stringindex [2]));
    }//GEN-LAST:event_btnLongActionPerformed

    private void btnReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceActionPerformed
        // declare variable to store input
        String aword = txtReplace.getText();
        //print and replace "a" with "x"
        lblReplaceAns.setText(aword.replace("a", "x"));
    }//GEN-LAST:event_btnReplaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStringMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaps;
    private javax.swing.JButton btnChar4;
    private javax.swing.JButton btnFound;
    private javax.swing.JButton btnIdentical;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnLong;
    private javax.swing.JButton btnReplace;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCapsAns;
    private javax.swing.JLabel lblChar4Ans;
    private javax.swing.JLabel lblFoundAns;
    private javax.swing.JLabel lblIdentical;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JLabel lblInstructions3;
    private javax.swing.JLabel lblInstructions4;
    private javax.swing.JLabel lblInstructions5;
    private javax.swing.JLabel lblInstructions6;
    private javax.swing.JLabel lblInstructions7;
    private javax.swing.JLabel lblLengthAns;
    private javax.swing.JLabel lblLongAns;
    private javax.swing.JLabel lblReplaceAns;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCaps;
    private javax.swing.JTextField txtChar4;
    private javax.swing.JTextField txtFound1;
    private javax.swing.JTextField txtFound2;
    private javax.swing.JTextField txtIdent1;
    private javax.swing.JTextField txtIdent2;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtLong;
    private javax.swing.JTextField txtReplace;
    // End of variables declaration//GEN-END:variables
}
